# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=false

# Game Properties
minecraft_version=1.21.11
enabled_platforms=fabric,neoforge

# Mod Properties
archives_base_name=modflared
mod_version=1.6.0
maven_group=de.rafael
mod_minecraft_version=1.21.11

# Loader Properties
fabric_loader_version=0.18.2
fabric_api_version=0.139.5+1.21.11
neoforge_version=21.11.6-beta

# Modrinth Properties
modrinth_project_id=modflared

# Curseforge Properties
curseforge_project_id=997330

# Publish Properties
mod_version_type=release